// Faithful reproductions of Karl B. Douglas's historical MicroCap Review articles.
// Original text preserved; only basic cleanup applied (removed figure/table captions,
// author bios, contact blocks, and duplicate per-article advice disclaimers; fixed
// obvious OCR/typo artifacts). Present-day interpretation lives in clearly-labeled
// "2026 Retrospective" fields, NOT in this original text.

export const CRISPR_2016_THESIS = `2015 was a prolific year for biotech IPO's. The year however, culminated with a dip in fourth quarter pricing, and speculation that a biotech bubble was forming. In our last issue we opposed the "bubble idea" and put forth an alternate thesis that over the last fifteen years, three essential process technologies fundamentally changed the biotech industry, resulting in faster, more effective innovation: mapping of the human genome, informatics and HTS or high throughput screening. As the cost of gene sequencing, informatics and HTS became dramatically lower, these technologies became ubiquitous resulting in increased potential for unprecedented biotech innovation. Consistent with our theses, we are seeing the full manifestation of this in today's biotech industry.

These disruptive technologies, which are now industry standard, were foundational to the impressive drug pipeline that fed the 2015 crop of new issues, and will continue to provide an ever growing pipeline of pharmaceutical innovation for decades. We constantly encourage investors to review R&D processes as an essential component of due diligence, to understand if these methods of discovery are used to drive innovation within target investments. And we put forth the idea that investments that have relied on informatics and HTS in particular are likely to have increased probability of success. In general, biotech investors should gravitate toward companies that rely on these techniques.

Just within the last two years, a fourth disruptive technology, possibly the most profound of all, was discovered which is spreading rapidly throughout the biotech community, the use of CRISPR. There is tremendous irony in the idea that the biggest biotech innovation in the last 15 years, arguably to date, was derived from a process developed over five billion years ago by our prokaryotic ancestors. Pronounced "CRISPER", CRISPR is an acronym: Clustered Regularly Interspaced Short Palindromic Repeats. CRISPR is essentially a component of the immune defense of prokaryotes such as bacteria.

CRISPR's work with CAS enzymes, or proteins (CRISPR Associated Proteins, such as CAS1, CAS2, CAS3 & CAS9) to intercept invading DNA, e.g. viral DNA. The primary mode of action is the CRISPR guide RNA, which essentially transcribes invading "enemy" DNA to determine if the DNA is compatible. If the DNA is incompatible it is bound to CAS proteins which impede replication of the DNA, a process known as protein interference. But if the DNA is compatible or beneficial, it is cleaved and added to the bacterial DNA as an enhancement.

Leveraging the ability to cleave and incorporate, scientists have adopted techniques to harness the CRISPR mechanism and modified CAS proteins for the purpose of gene editing. Gene editing is not a new field, and there are other techniques. However, CRISPR gene editing holds tremendous promise for therapeutic application. Imagine being able to cheaply and easily "knock out" undesired genes such as the dreaded p53 cancer gene or Huntington's HTT gene.

As promising as gene editing is in the context of mammalian and human therapeutic applications, it will be many years before the complexity of this technique will see prime time application as a true gene editing tool in mammals.

But CRISPR is quickly establishing itself as the gold standard for other research techniques, the most significant of which is use of CRISPR as a screening mechanism, to quickly and easily identify potential drug targets. Before CRISPR, HTS (High Throughput Screening) was the state of the art means to screen. And state of the art HTS robotics today are able to screen at a rate of one compound every 3 – 4 days. Even today this is considered a blinding speed compared to the methods as recent as two years ago.

So the excitement about CRISPR is well deserved. Not only has this technology brought about a new level of therapeutic potential, it is currently leveraged as a much more efficient precursor to traditional robotic HTS. By leveraging CRISPR to predict protein binding, the technique can eliminate thousands of potential protein targets in a single test process, shrinking years of trial and error to a single experiment. So rather than using HTS to screen for example 1,000 compounds over a period measured in years, CRISPR can reduce that group to hypothetically, 10 and HTS can then complete more specific testing in, again hypothetically 40 days. For the biotech industry, this is a leap forward on an unfathomable order of magnitude! Imagine the time, R&D cost reduction associated pipeline impact of eliminating so many candidates so easily. No doubt CRISPR is going to have a tremendous impact on the efficiency of drug discovery.

In terms of the investment world, for investors searching for early stage blockbusters, targeting companies using CRISPR as a screening tool seems like a great way to hack the complexity of handicapping R&D success. In broader investment terms, there are two ways to look at CRISPR. The first is the profound application of true gene editing, for example to "knock out" a gene such as HTT (Huntington's). And there are already many public and private companies involved in this aspect of CRISPR. We see gene editing triggering a number of biological and ethical issues that may take at least a decade to resolve. So exercise caution on swinging for the fences on this approach.

The second, and what we see as more immediate term is the use of CRISPR as a screening tool to dramatically accelerate the identification of drug candidates. This aspect of CRISPR is a realistic use of CRISPR today. Companies leveraging CRISPR in this way are likely to have reduced R&D costs, accelerated discovery and overall more productive pipelines. And so we believe this is an excellent way for investors looking for the next blockbuster to hack the complexity of biotech due diligence.`

export const COAL_2016_THESIS = `Coal will slip behind natural gas in 2030 and become the third fuel worldwide. This will last well beyond 2040. Run a quick search on "coal and dead" and you'll get hundreds of articles projecting the death of coal. Recent bankruptcies effecting once considered "invincible" companies such as Peabody Energy, Arch Coal and Alpha Natural Resources, has led many to conclude coal is in fact a dead sector, relegated to the buggy whip graveyard. But the Energy Information Administration (EIA), a division of the Federal Government says otherwise. How often do you get to invest in an industry responsible for supplying 33% of a $15 Trillion dollar economy's electricity demand for pennies on the dollar?

Indeed the short term outlook is far from obvious as coal's share of electricity generation will continue to fall. Coal was burned to generate 50% of US electricity production in 2005 and 33% in 2015. It is projected to fall to 21% by 2030 and eventually 18% by 2040. How do you make money in an industry slated to shrink by 27% over the next 14 years? Invest in strong balance sheets! It's the un-leveraged companies that will emerge as tremendous cash flowing opportunities offering growth fueled by massive industry consolidation.

Many of the recent bankruptcies are arguably self-inflicted; the result of significant overleverage, in some cases as much as >10X EBITDA. The onset of abundant low cost natural gas, a competing fossil fuel, directly offset a significant percentage of the coal burn through "coal-gas switching". In fact the industry contracted 34%, with electricity from coal dropping 17 points from 50% of all electricity to 33%. The resulting commodity price drop, margin erosion, over leverage and a decade of anti-coal lobbying and media presence by environmental activist groups, produced a coal industry in a tailspin! So what makes this pariah of an industry potentially tomorrow's darling of an investment opportunity? Things to consider:

- **We can't do without it!** Even under the most aggressive EPA assumptions, coal will still represent about 10% of US energy consumption by 2040, a quarter century from now. It will still be used to generate 18% of US electricity by 2040, a statistic that must be quite a disappointment to green lobbyists.
- **Scrubber Capex Investment** – The power industry has already invested over $500B in environmental remediation equipment such as NOX/SOX scrubbers. They will need the depreciation from these investments to keep electricity prices down.
- **Low Gas Prices Unsustainable** – Gas prices are rising steadily as environmental regulation increases and exploration activities become more costly. Rig count has fallen to a three year low and at costs above $2.50 per MMbtu, coal starts to look competitive again.
- **Global demand will continue** – India and China will remain the largest consumers of coal through 2040. The EIA forecasts coal consumption to grow at the slowest rate of the competing fuels, at a mere .6% per annum.
- **No alternative for steel production** – We haven't found a steel making alternative to the use of metallurgical coal in the steel making process.
- **Fresh balance sheets** – Previously over-leveraged companies that emerge from bankruptcy and newly formed companies managing the vestigial assets of the doomed ones will have stronger balance sheets and hopefully debt-phobic management.
- **Renewables benefit from coal** – Newer transmission lines built to support renewable power producers would be financially unsustainable without the additional use by base load power producers that generally utilize coal for their base load generation.
- **Technology** – Coal can be burned with zero emissions if the right technologies are used. As energy production costs continue to rise from competing sources, clean coal will reemerge as a cheap source of energy, potentially tipping the scale back in favor of the black stuff!

Before you open up your online trading account and start buying coal stocks, there are some very important considerations to keep in mind. In terms of coal production forecasts, the numbers vary significantly. CPP or Clean Power Plan is an EPA initiative to reduce CO2 emissions. Ultimately if this plan gets fully implemented, US CO2 emissions will be reduced by 45% relative to 2005 levels by 2040. As the forecast indicates, there can still be a significant delta in demand, particularly starting in 2019, where under the CPPHOGR scenario we see demand fall to 650M tons by 2025. But there's a silver lining in all these numbers! According to the EIA, US utilities burned 740 million short tons in 2015. So three of the four most severe scenarios already call for more production than is currently available. And with the most recent announcement of Alpha Natural Resources, additional production will go offline. With 650M tons of thermal coal supply, well run companies should be able to achieve reasonable cash flow.

The characteristics to look for are quite simple: minimum leverage, low reclamation liability, low production cost. Production cost is usually a function of reserve quality and logistics. Forward sales price is also significant. Companies with long term off-take agreements will offer significant ability to ride out short term dips in the market which based on EIA forecasts are expected between now and 2020.

In the Microcap segment of the market, Hallador Energy Company (NasdaqCM: HNRG) is worthy of tracking. The company is in the stable Illinois Basin. It has a market cap of roughly $134M. Once again this company has demonstrated fiscal discipline, debt is roughly $250M with EBITDA of $85.38M as of 3/31/2016. Their operating margin is 13.46%, slightly lower than much larger analogs such as Alliance Resources, ARLP. We think HNRG will be interesting if they can make smart acquisitions with low to no leverage, and grow their footprint.

Foresight Energy LP (NYSE: FELP) is another Microcap with market capitalization of roughly $209M ($1.60 per share as of 7/5/2016). FELP is a significantly larger company. The company reported TTM revenues of $912.02M with EBITDA of $236.64M. Total debt is $1.6B, and operating margins are reported as of 3/31/2016 of 4.5%. We believe the leverage profile of FELP demonstrates the same type of risk profile that has brought down many of the majors. We consider over-leveraged assets (more than 5X EBITDA) an insurmountable risk in this market place. On an EV/EBITDA valuation basis, FELP is significantly overpriced relative to its peers.

The volatility in the coal sector will continue to test the mettle of coal companies through 2020. Only the companies that have minimal debt will survive. We believe many of the choice assets that will become available through the bankruptcy process will be acquired by private equity sponsored companies. Those same PE companies will seek to exit into the IPO market and a sector of hopefully deleveraged assets will join the publicly traded coal sector.`

export const INDIA_2016_THESIS = `According to Goldman Sachs Global Research, the top three performing economies for 2016 will be India, China and Indonesia in that order. China is obviously already well established in US capital markets, with roughly 198 ADR (American Depository Receipt) listings and a plethora of other issues listed directly on US exchanges. All sizes of Chinese companies are represented, from Large Cap to Micro Cap. Indeed there is no shortage of supply for institutions seeking China exposure. By contrast, what we find shocking, is the world's top performing growth economy, India, is totally underrepresented in US markets.

Actually there are only 12 Indian ADRs listed in the US totaling roughly $440B of market cap. And of that, roughly $308B is contributed by one issue, HDFC Bank Ltd., NYSE-HDB. We expect institutional thirst for Indian equity exposure to increase substantially based on the China slow down and the relative decimation of commodity based BRIC economies such as Brazil and Russia. This supply demand imbalance, combined with inefficiency of capital availability in India domestically, should naturally create a flow of companies seeking the advantages of US listings.

The Bombay Stock Exchange is the major trading venue for Indian companies and their stocks. It's the world's 11th largest stock exchange with more than 5,000 companies listed. Aggregate BSE market capitalization exceeds $1.7 trillion. Where liquidity in the top 100 issues is quite respectable, liquidity becomes a challenge in the smaller company equities. These companies would be well served to consider level II ADR listings in the US. ADR listing of this class of security would attract US institutional investors that have resisted buying domestic Indian issues due to currency risk, added costs and in certain cases, exposure to non-US securities laws and taxes.

Although the listing standards on the BSE are quite rigorous, the vast majority of US investors prefer the governance and transparency requirements of the US exchanges. For companies already listed on the BSE, the ADR process is quite straight forward.

The basic ADR listing process is the Level I listing process. And although there are some benefits such as providing a transition path for companies ultimately seeking national exchange listing, Level I does not provide the depth of investor access since securities under Level I are restricted to trading OTC.

However, the level II ADR listing process allows companies to trade domestic share equivalents on a US national exchange. For qualified issuers, this listing process is the quickest path to achieving improved liquidity and eventually more efficient price discovery. With Indian ADR's in particular, quite often because of the under supply, Indian company ADR's trade at a premium to the ordinaries.

Level III ADR process actually combines national exchange listing with a capital raise. For lesser known companies, the processes inherent in "IPO securities offering activities" for example the roadshow, serve to not only raise capital, but to educate buy side investors on the merits of owning the equity.

Overall, the ADR listing strategy is an excellent way to attract a much broader investor base into a particular security. Listing on a US national exchange will also contribute to the prestige of lesser known Indian equities and promote more efficient price discovery. Where the American Depository Receipts processes require that a company is already listed on an exchange locally, those companies that are privately listed, have the option to list domestically and pursue the ADR process, or they can consider a direct offering to the US markets. It's this last category that quite possibly will create the best investment opportunities for US investors.

Private equity investors have enjoyed a significant pool of mature cash flowing companies from which to choose in India. High returns have been consistently generated from the significant number of competitively priced private equity deals that are available in India. There are numerous sectors where multiples are considerably lower than their US equivalents. Another factor that may contribute to a wave of Indian IPO's is the desire to monetize growth and take money off the table. According to McKinsey Research, of the $51 B invested in private equity, only $16B has actually exited. US markets may offer an alternative to limited exit opportunities in India. With the improved liquidity for US investors and improved price discovery, PE investors may be able to exit at competitive multiple directly into the public companies.

All of these factors lend themselves to support for more Indian companies preparing ADR and IPO transactions for early 2016 and beyond. And for MicroCap investors and issuers, we expect to see stepped up activity in the asset class for 2016.`

export const RAISING_CAPITAL_2017_THESIS = `2016 represented a year of surprises in many areas. While we were entertained (or stressed out) by the election, many significant changes took place in the markets. We saw the coal industry go from bust to boom, and shale oil go from boom to bust and ultimately to stability all within 12 months. In addition we saw the Microcap market outperform every other market by capitalization. 2017 looks promising for the markets given some of the tax legislation being proposed. Now more than any period since 1998, Microcap CEOs should be on the trail hunting for that elusive capital. And investors will be itching to find great deals. So we've compiled seven of the best practices we observed in 2016 for raising capital to arm CEOs with some solid ideas as they hit the trail in 2017.

The Microcap market has existed for decades going back to the 1970's. Once called the "Pink Sheets" referring to the 5" by 18" stack of pink quotation sheets which were collated and printed daily for market makers, and often referred to as the Penny Stock market, the Microcap market has evolved significantly. Fifteen years of SEC regulatory reforms, and tighter FINRA regulation has changed the Microcap market for the better, to a point where it is fast becoming a legitimate capital raising forum for CEO's seeking an alternative to the perceived "limited options" of the venture capital and private equity markets.

US public companies with market caps of $250M or less, so called "Microcaps" now exceed $200B, yes BILLION, in aggregate market capitalization across all US exchanges. It's hard to argue that a $200B market is anything but legitimate. And that fact is being further echoed by value hungry institutional investors seeking returns that outperform the major markets. It's fair to say that the Microcap market is still evolving. With the winds of opportunity filling the sails, what do CEO's need to know to tap into this exciting alternative?

Seasoned institutional investors such as Perrit Capital, Heartland Advisors and others have developed substantive methods of due diligence that allow them to value hunt effectively. And with the presence of serious institutional funds investing in Microcap stocks, CEO's have an unprecedented opportunity to develop a "direct to investor" audience. We examined the successes and failures of several companies that we met in 2016, during various phases of capital raises to identify the common best practices being leveraged in the Microcap market. Here are seven commonalities that we observed during 2016:

### Understand the market

Just understanding that you're competing with almost 6,000 companies for capital is a great start! The most common point among the successful CEOs and other management officers that we met during the year was that they understand the market dynamics very well. They understand that there are many institutional investors seeking out-sized returns, "seeking alpha" based on pure fundamentals of equities listed in the inefficient OTC market. Gone are the myths that "institutional investors do not invest in Microcaps." Their conviction was bolstered by the knowledge that over 1420 of the Microcap companies currently have institutional ownership of over 10%. Most companies recognized that NASDAQ was the ideal exchange on which to be listed. But most recognized that there is value to being listed on the OTC. In general most understood that there was significant interest in various forms of PIPE (Private Investment in Public Equity) offerings. And for good reason, according to PrivateRaise.com, $82 Billion in PIPE transactions were completed during 2016.

### Institutional investors seek value

Management for the most successful transactions we observed understood that fundamentally speaking, Microcap investors are bargain hunters. They are looking for companies that can grow at outsized return rates. If your company is growing at a compound annual growth rate that is no different to the more seasoned larger mid cap companies, it's difficult to justify Microcap risk. Many of the more successful companies offered venture and private equity value propositions. We feel this is a critical success factor, and that both in deal structuring and marketing, it is necessary to offer venture and private equity returns with the promise of a built in "eventual" liquidity event as the market for the securities develops.

### Successful capital raises typically have an institution on board well before going public

Successful management teams generally leverage existing institutional relationships to help develop the public market for their shares. It's important that CEO's understand that their shares are designed to be sold. And large buyers are generally institutions that are familiar with the "story". Who's in the deal is often as important as the deal itself. Prestigious institutional presence often denotes that someone did significant due diligence and vetted the company and its management. Although Microcap institutional investors are value investors, they are driven by the need for capital preservation. Capital Preservation is code for "do we trust management". "Is there meaningful governance in place?". By attracting a major institution in the stock, and leveraging company relationships with the "anchor institution" CEOs can generate a significant ownership base. For early stage companies, the right institutional investor can be the difference between long term capital raising success and falling into the "OTC no man's land". It's all about sponsorship: Consider that most institutions queue up to invest in venture and PE funds. They do this for the professional management that ensure proper governance and board structures are in place, as well as proper management policies and procedures are implemented. So even if it takes a deep discount to attract an influential institution, we recommend the practice. Just make sure the institution in question is committing to put their name on the deal and work with management to do the work necessary. We strongly recommend recruiting a strong institutional investor to "sponsor" a transaction as critical success factor. Not only does this create the right perception of a company and its management, but the side benefits of oversight and proper governance help to avoid many of the strategic mistakes often committed in the Microcap space.

### Liquidity Building

It's very difficult to market your stock if you don't have a good story to tell! Needless to say, most of the successful deals we saw during 2016 had a very solid story that was easily articulated. It was the disruptors that prevailed in 2016. Combine faster and cheaper with effective management, performance and solid corporate governance and many investors paid attention. The successful CEO's developed a deep management bench, and allocated a significant amount of time "pitching" buy side investors on the fundamentals of their story. The successful companies went well beyond the traditional IR, and went to direct email campaigns to institutional investors, as well as a consistent presence at the major conferences. Public relations is an area that many companies overlook. We noticed a trend toward more PR than IR. After all PR is generally more targeted at marketing the products and services of the issuer than marketing the stock. But an effective PR campaign has an added benefit that many investors will look to invest in what they see selling.

### Dual listing

Several international markets offer ways to augment liquidity development by attracting alternative investors. High net worth retail, often viewed as a necessary component of a robust liquidity strategy, is a very tough nut to crack in the US for newly listed issuers. Brokers typically cannot solicit retail orders of shares under $5 per share. And many US retail broker dealers have moved to managed money platforms as compared to stock picking. This limits retail orders to investors that hear about the company through public relations exercises. However our neighbors to the north offer several well regulated exchange venues and retail brokers that perform more traditional investment banking roles, recommend high value opportunities to non-US investors. Although dual listing on Canadian exchanges doubles regulatory obligations, it's well worth it if management can get the backing of a good investment banker. We have had success with firms like GMP Securities and Canaccord Genuity. Australia also offers compelling investment options through the ASX. And like Canada, offers more of a traditional investment banking option for microcap companies. In fact, Australia provides a gateway to other Asian investment markets.

### Alternatives to equity

Growing the balance sheet doesn't always require equity offerings. In fact we saw several companies achieve significant growth during 2016 without any significant equity issuance. In many case companies were able to access debt at competitive rates in the BDC "business development company" market. BDC's offer debt to companies with historical cash flow, where sometimes the borrowers fall short of traditional bank criteria. Many BDCs consider the full disclosure of public companies as a benefit. In addition, for early stage companies, venture lenders and receivables finance are excellent low cost alternatives to equity issuance. Although basically an equity structure, ATM transactions allow companies to access capital with less equity sales. It's sell as you go! ATM or "At-the-Market" offerings were the second most popular form of PIPE during 2016. 37.4% of 2016 PIPES were ATM deals. This relatively new structure is best suited to issuers with well developed liquidity and also ability to complete a registration statement. During 2016 many ATM transactions were completed at less than 8% discount to market, with no warrants. This new structure is often misunderstood by issuers and confused with "toxic convertible notes". The primary difference is a note allows the owner to convert and sell without the consent of the borrower (subject to certain limitations such as price floor). However with an ATM, generally speaking the issuer is in control of issuance. For companies with strong liquidity profiles, this is a useful vehicle leveraged by many successful capital raisers in 2016.

### De-Risk your deal for your audience

In the current market there is no substitute for authenticity. The days of the basic "all upside, no competition" pitch are over. We have seen this trend develop over the last few years. Successful managers are actually helping their investors to "de-risk" a transaction by frankly and openly defining the risks and weaknesses their companies face. Speak openly about your competitive threats. It's your strategy to outmaneuver the competition which is important. And use the competition to show what a great value you are offering. Although this may seem counterintuitive, portfolio managers are more concerned with identifying the risk in a transaction than in identifying the huge growth that most CEO's think they are interested in. Preparation of investment materials which go beyond "basic risk factors" to an in depth analysis, often lead to a meaningful conversation, and positive results.

These critical success factors are far from comprehensive as issuers need to put significant effort into choosing service providers such as investment banks, advisors and counsel that have proven track records. We compiled this list because selecting an effective IB, counsel, an audit firm and IR firm is not an automatic formula for success. As with everything success is usually a function of hard work and tireless attention to detail. The seven "extras" we identified are common among many successful Microcap CEOs. We hope this list will dramatically improve your chances of a successful capital raise in 2017!`

export const PPJV_2017_THESIS = `The Dow has been climbing at a breathtaking pace, reaching a record high of 22,000, a significant jump from 17,000 in 2016. Whatever the underlying assumptions driving this growth, it's clear that Keynes' "Animal Spirits" are running wild! This economic improvement has had an impactful cross over effect on the private equity markets, pushing valuations to sky high multiples and leverage ratios to levels unseen since the pre-crash hay days. Undeployed capital chasing investments in privately held companies has grown considerably. The question is, "Does this trend represent an opportunity for MicroCaps — traditionally limited to dilutive ATM and convertible debenture transactions — to change strategy and achieve significant high growth financing? And further, what are the best structures to consider?" We believe the Private Public Joint Venture, or PPJV, is the structure MicroCap CEOs and their Boards of Directors should explore.

Capital overhang in private equity is currently over $700 billion. Yes, that's correct $700 Billion. Based on recent PIPE (Private Investment in Public Equity) activity over the last six months, some PE money is crossing over into the public markets. And yet, MicroCaps are still struggling to attract capital at competitive terms.

According to Placement Tracker (PlacementTracker.com), PIPE deal volume is down 2.8% (469 deals in H1 2016) and dollar volume decreased a massive 44% ($27B in H1 2016). A logical analysis of these numbers infers that PE managers have two possible course of action: to start sending money back to investors, or get more creative.

PIPE activity was well distributed across sectors, with financials leading the way. Many of the sectors which are typical mainstays of private equity are showing considerable activity. That includes the energy and basic materials sectors, which typically represent a high concentration of MicroCaps.

Similar to 2016, the instrument types typically favored by PIPE investors have not changed. Registered common equity and ATM transactions have led the way. Both tend to favor more mature companies with market caps well in excess of $100M. These companies have the daily trading volume and VWAP profiles to allow companies to finance with these types of instruments without detrimental effect on share price. The reality is that unlike the larger Small Cap PIPE issuers, many MicroCap companies are limited to selling shares at discounted prices with warrant coverage, or selling convertible debentures that convert at discounts to market.

We picked a few random examples from 2017 to demonstrate the effect of each major transaction type on sub $10M issues. Where our analysis is not purported to be statistically accurate for each transaction type, we highlight the results using common examples of public issuers to examine the impact of certain structures. The companies selected were chosen randomly, and all information used was publicly available at the time. Our conclusions are not buy or sell recommendations, nor do we have any opinion on, or financial interest in, the specific issuers.

The first transaction type is a CMPO, or Confidentially Marketed Public Offering. Marrone Bio Innovations, Inc. Nasdaq CM: MBII announced a $9,200,001 offering on April 24, 2017. The offering was issued at a 20% discount to the company's share price which at the time was $1.75. By August the company's share price dropped to $1.11, a 37% decrease. Without delving into the specific operations of MBII, it is clear that the combination of discount to share price, and sudden increase in share volume created a negative impact on price. This is a very common story for MicroCap issuers.

In addition to CMPO's convertible debentures have been a mainstay of the PIPE market. We picked an offering that took place on the same day as the MBII offering in a different sector to demonstrate the effect. On April 24, 2017, Reed's, Inc. (NYSE MKT (AMEX):REED) announced that it raised $3,400,000 in a Convertible Secured Notes transaction. The fixed conversion price of the Convertible Secured Notes was $3.00 per share, an approximate 36.84% discount to the market price ($4.75 at the time) of the REED deal announcement. A series of 1,416,667 60-Month Warrants (125% Coverage) with an exercise price of $4.00 per share (8.05% discount) was issued to the investors in this transaction. As the chart indicates, on August 11th, the closing price of REED was $1.60, down 66%.

The two examples are representative of the broader experience of illiquid MicroCap issuers with traditional PIPE structures. Clearly there must be a more effective way for MicroCap issuers to raise growth capital. When the status quo cannot go on we must adapt, innovate or die. In this instance, we believe the solution may lie in a strategy wherein MicroCaps partner with private equity, opening up access to the current $700 billion private equity overhang. This strategy is particularly suited to companies pursuing an active M&A strategy such as data center roll ups or mining consolidations. Given the heavy commitment by PE to the E&P sector, energy companies are uniquely suited to the strategy.

This structure allows management teams to execute their business plans and create shareholder growth without excessive dilution or "technical" erosion of market cap due to oversupply of shares with insufficient liquidity. Over the years we have met hundreds of MicroCap CEOs and their management teams. In general, we see highly motivated managers that could execute exciting plans "if only they were adequately capitalized." We believe the market is ready for a new transaction type, the PPJV or Private Public Joint Venture. The PPJV brings both the public company issuer and the private equity investor together in a symbiotic relationship that meets the requirements of both worlds.

Let's examine the pros & cons for the MicroCap operator:

### Pros for the MicroCap operator

- Non-dilutive — Pubco shareholders experience the benefit of pubco share of the JV cash flow without excess dilution.
- Acquisitions are accretive to pubco earnings.
- Financial stability — commitment of long term deep pockets of the PE company.
- Easier access to low interest leverage.
- Experience and expertise of PE management particularly in the M&A process.
- MicroCap management team can focus on building shareholder value, and spend less time raising money.
- Access to higher quality investors.
- Access to higher quality acquisition targets.

### Cons for the MicroCap operator

- Non-consolidation of assets. Generally speaking, the pubco initially has a minority position, and may not have board control. However, this is not always the case.
- Potential double cost of management between Pubco and JV management.

### Pros for the PE investor

- Built in exit option — by electing to convert JV equity interest into shares of the Pubco, or through phased divestiture, the PE investor has a built in public exit which can be phased over time.
- Higher exit value — since the PE company is converting, they are eliminating the illiquidity spread between private company and public company valuations.
- Greater financing flexibility — a properly executed pubco listed on a major exchange offers cheaper equity financing opportunities, particularly in difficult credit market cycles. Access to S3 shelf registrations can be a tremendous value.

### Cons for the PE investor

- Transparency — depending on structure of the JV, the PE company could end up with unwanted transparency.
- Higher costs — depending on how pubco costs are allocated, this could reduce earnings at the JV level.

We believe that the pros of the PPJV structure significantly outweigh the cons for both issuer and investor alike. And this structure could quite possibly become the next major trend in MicroCap investment as the concept gains popularity. With possible elimination of dilution, which has a detrimental impact on public shareholders, we believe the PPJV is a far more productive approach for raising capital.

PPMT Capital recently attended the Planet MicroCap conference in Las Vegas in April and test marketed the concept with attendees, including representatives from the mining and energy sectors. We sat down with Chris Jones, CEO of Uranium Resources, Inc, (NASDAQ CM: URRE). Uranium Resources, Inc. operates as an energy metals exploration and development company and is developing lithium brine basins in Nevada and Utah for exploration and potential development of lithium resources. Chris felt that the PPJV would be an interesting way to accelerate transition to production of some of the company's larger reserves.

Jericho Oil Corporation, (OTC: JROOF) is developing E&P reserves in one of the most exciting basins in the US, the "Stack" in Oklahoma. We were intrigued by the knowledge that Jericho was already leveraging the PPJV strategy with a strategic family office relationship. As a prime example of an early adopter, we'll be tracking Jericho to see how the impact of the PPJV impacts their development longer term.`

export const FAMILY_OFFICES_2018_THESIS = `Middle market growth companies have a voracious appetite for capital. It is incumbent upon management teams to know how to raise capital efficiently. Yet the fastest growing segment of the investment community is frequently overlooked. What's the fastest growing segment in terms of assets? If you're thinking ICOs, hedge funds or private equity, you'd be wrong! Over the last 10 years, a relatively new class of investor has emerged with an insatiable thirst for deals. If you guessed family offices, you're correct! Family offices are indeed the fastest growing segment of the capital markets. They are very private, so accurate data is hard to obtain. But the latest estimates are that family offices controlled between $3 and $4 Trillion in 2017, according to Bloomberg. And that number is growing significantly as UNHWIs or ultra high net worth individuals are minted in fast-growing economies such as China, Vietnam, and Indonesia.

### History

The family office concept dates as far back as the 8th century in Europe, and even further back in China, where dynastic families controlled vast wealth and property, with accounting and reporting procedures that would put many modern-day institutions to shame. The first well-documented example of the family office in Europe was the Medici family, founded in 1169. Known as the Medici Bank, the Medici family were the wealthiest family in Europe, and in addition to financing trade, financed whole governments. 19th century Europe produced the Rothschild Family, and in the U.S., The House of Morgan, followed shortly by the Rockefeller Family and others. Today there are over 2500 family offices worldwide.

Family offices come in all shapes and sizes ranging from $100M on the low end to several billion on the high end. Some follow very disciplined low-risk investment models, such as multi-family residential housing only, but most diversify their risk across strategies ranging from venture capital to public markets. I was talking to a colleague a few months back, who told me I'm wasting my time with family offices because "they only invest in real estate". Nothing is further from the truth.

Where it is accurate that many Single Family Offices have real estate strategies, their holdings can be quite diverse. Consider TPG Capital founder David Bonderman's family office, Wildcat Capital Management. According to Insidermonkey.com, AUA (assets under administration) of Wildcat, are now more than $2.3B. And according to public filings, Wildcat has made a significant number of public company investments. The number of family offices is growing fastest in Asia. This is a result of the tremendous economic success in China, Korea, Vietnam, India and Indonesia.

### Streamlined Decision Making

One of the most attractive aspects of the single-family office is SFOs manage their own capital. Decisions are usually fast, and are not laden with the layers of committees which are often typical of major institutional investors. SFOs offer many advantages over other investors such as hedge funds. In most cases when presenting a deal, you're sitting across from not only the decisionmaker but the owner. Many companies often make the mistake of assuming that when presenting to a manager at a hedge fund or private equity company, they are sitting across from "the money", while in reality, they are presenting to an analyst designed to evaluate your deal. You are rarely pitching "the money", so SFOs represent one of the few chances. But be on your game, you're sitting in front of the intellectual horsepower that created the family office in the first place. They understand a thing or two about business.

In many ways, family offices are nirvana for the microcap CEO looking for an anchor investor. So why aren't most management teams focusing efforts on family offices? The first reason is the sector is so private that it's off the capital raising radar. In fact, most SFOs do not have people on staff to market the availability of capital like a hedge fund. So SFOs usually see less than 5% of the activity in a sector.

Secondly, the family office ecosystem has its own protocols and language. Understanding the various terms and protocols is critical to success. For example, there are SFO's (single family offices) and MFOs (multi-family offices). We've explained the clear benefit of the SFO, but it gets more complicated with the multi-family office structure. MFO can mean a lot of things. For example, (a.) are they actually managing the SFO funds with discretion to invest? Or (b.) are they recommending deals to the SFO subject to the SFO approval. You can achieve closure with either structure, but obviously, the discretionary account is best. There's a "c" scenario in which some MFOs are purely service providers for legal, regulatory and administrative services, and leave investment alone. They may refer your deal to a client as a favor, but it's unlikely the client is relying on their recommendation. So understanding the type of MFO, a, b or c, can save a lot of time.

Entering the family office universe can be difficult. Where most institutional funds have origination platforms that encourage inbound inquiries and are equipped to manage the process, most SFOs do not have this infrastructure. Deals that come in "unsolicited" go into a pile. And there's no guarantee anyone will ever review the deal. So the best way to approach an SFO is to approach through a trusted advisor. Usually, that's an accountant or a lawyer for the family. Accountants, in particular, are always willing to review a deal because they have the skills to understand the fundamentals. If they think its sound, they are happy to refer, because referring a good deal is considered "value add" for them. Purchasing a family office list and cold calling or even worse, mailing unsolicited teasers is a waste of time. The family office ecosystem is one based on multi-year trusted relationships. Do your research and learn who the advisors are for the SFO. Look at deals they worked on in the past and find a common tangent. That's difficult and time-consuming!

### Hack the marketing

Remember that family offices want great deals! They don't see enough and routinely go to conferences in search of transactions. Last year I ran into several family offices at the Planet Microcap conference. I expect their presence to become more common as they reach out to more venues in search of deals. There are several regional and national family office associations that hold conferences. The Wilson Family Office Club offers services ranging from capital raising boot camps to presentation opportunities. Conferences consolidate buyers and offer the most efficient way to meet family offices. Many of these conferences are full of accountants and lawyers offering their services. Optimize their presence by asking "do you work for any family offices". If the answer is yes, then you may be able to leverage their relationship. And they'll be happy to help in the interest of getting your business.`

export const AI_2019_THESIS = `Our fourth article on family offices for Microcap Review focuses on new investment trends in the family office investor space. Recently we've seen increased activity in AI and 4IR, the Fourth Industrial Revolution economy. In this article you'll learn about the components of 4IR, two breakthroughs in artificial intelligence, and eight markets that will experience hyper growth over the next five years.

The second half of 2018, and to a greater degree, the first quarter of 2019 has been marked by a continued expansion of family office mandates from the traditional focus on real estate assets to more diverse investment strategies. Smart money is smart via its ability to identify and capitalize on mega-trends before those trends become mainstream. And the major anomaly that we've seen develop since last year is a spike in inquiries about investments in artificial intelligence. Of course, family office CIOs and other advisors are routinely attending World Economic Forum events. And Klaus Schwab, its Executive Chairman has been a leading advocate of the concept of The Fourth Industrial Revolution (4IR), which leverages artificial intelligence as the integrator of everything from 5G communications to biological systems and cyber-physical systems.

### Reason 1: Biggest Economic Catalyst in 150 Years

With an estimated CAGR of 59.8%, AI is too big to be ignored. The smart money realizes that sitting on the sidelines is tantamount to putting money in a mattress. Imagine knowing what you know today about the last 100+ years of economic history, and being a peer of John D. Rockefeller, Henry Ford, Alexander Graham Bell, Thomas Edison, and Charles Babbage. Your "crystal ball" would have resulted in one of the more impressive investment portfolios of all time, because you'd have gone long in the petroleum, automobile, telecommunications, power and computer sectors in their infancy before most investors understood that those industries would define the 20th-century economy i.e. shorted dying industries and investing in the emerging ones. AI, and the Fourth Industrial Revolution that it's creating is the modern-day equivalent of that period, but with logarithmic proportions.

### Reason 2: Advances in ML and DL are Unprecedented

Ask anyone in the AI field to describe artificial intelligence and they'll talk about Machine Learning (ML) and Deep Learning (DL) as the two major components. Where these two components are the basis of AI, in translation they bear little resemblance to the actual effect that AI will have on our economy, sociology and culture. That being said, it is useful to have a basic understanding of the two components.

Machine Learning, or ML, relies on algorithms and statistical formulas run on an iterative basis to "learn" and generate an algorithmic understanding of a dataset. In effect, rather than requiring a programmer to code specific instructions based on his/her knowledge, the computer analyzes data and "learns" based on a defined data set, and refines and produces a series of valuable algorithms. Take driver automation for example, the computer analyzes programmer-defined data such as maps, obstacle data, traffic rules and laws and derives a series of complex algorithms to seamlessly guide a level three enabled autonomous vehicle down a major highway without incident. In ML, the dataset is largely defined.

### Reason 3: The Adoption Cycle is Getting Shorter

Deep learning is the next generation of ML in the sense that DL is unstructured. In DL, the program analyzes all data, determines all correlations and determines its own datasets and algorithms, not a predetermined subset, and identifies correlations, and then creates algorithms. Imagine a program that rather than figuring out how to move a car down a highway, analyzes all available data and correlations and designs the most efficient way to move people from point A to point B. That is the second generation of ML. It's far closer to what we view as invention. So, imagine an inventor that can seamlessly access terabytes of data — the speed and complexity of innovation is infinite and the rate of adoption is shrinking.

Welcome to the fourth industrial revolution. Time is being compressed and innovation is increasing at a pace beyond our comprehension. For a basic investment approach look at the requirements of AI. By its very nature, AI uses and creates a massive amount of data. This data (data storage, data processing and ability to manipulate these massive amounts) translates into the three core categories of investment opportunity. In effect, data warehousing, data mining and networks are broad categories of investment opportunities.

### Reason 4: Many Entirely New Business Types Are Created

In terms of data processing, think in terms of GPU manufacturers such as Nvidia that participate in the AI processing arena. The value associated with the ability to move the massive amounts of data that this model requires lies in the rollout of 5G. So think 5G value chain. And data storage is tantamount to the modern utility. However the fourth industrial economy, or AI economy, will reach far beyond those three areas.

Smartphones and Smartcars (autonomous vehicles) have the most dramatic influence on the consumer. These devices will become the primary technology interface until home-based robotics are introduced. The image recognition technologies incorporated into these technologies will dramatically enhance functionality as well as create hyper growth for the camera component manufacturers. And the combination of AI chips, and additional AI programming will dramatically enhance the user experience in both examples. From the hardware perspective alone, the revenue growth could be significant. Certain technological breakthroughs which have been in the works for the last 15 years are poised to drive significant growth.

### Reason 5: Predictable Growth

Just nine years ago, NEC was the standard with 72% accuracy vs the human benchmark of 95% accuracy. As of 2016, computers are 97% accurate in image recognition, two percent better than the human eye. From an investment perspective consider the various components of the image recognition value chain. From the lens manufacturers to the chip manufacturers, these companies will see significant growth.

An example of this is the average smartphone currently has one or two cameras. However, by the end of 2019 the average mobile phone will have eight cameras to support the growing image recognition functionality. Smartphone camera component suppliers will see 8x growth in revenues based on current requirements. Similarly, the average L3 smart car or autonomous vehicle has upwards of twelve cameras.

The numbers are staggering just across the smartphone and smartcar markets. Robotics and industrial automation will be another hypergrowth sector. But there are many additional areas, including drones and drone applications, IoT, or internet of things, shipping, and logistics, augmented reality, and surveillance. All are poised to be major growth areas within the Fourth Industrial Revolution. Hold on to your wireless ear buds.`
